[package]
name = "py-web-audio-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "py_web_audio_api"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.21.1"
web-audio-api = "1.2.0"
